In [1]:
x = [35, 76, -43, -36, 12, 3, 24, -45]


8-element Vector{Int64}:
  35
  76
 -43
 -36
  12
   3
  24
 -45

In [2]:
sort(x)

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [3]:
x

8-element Vector{Int64}:
  35
  76
 -43
 -36
  12
   3
  24
 -45

In [5]:
sort!(x)

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [6]:
x

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [7]:
function padwithzero(vector, n)
    x = [zeros(n); vector; zeros(n)]
    return x
end

padwithzero (generic function with 1 method)

In [8]:
padwithzero(x, 3)

14-element Vector{Float64}:
   0.0
   0.0
   0.0
 -45.0
 -43.0
 -36.0
   3.0
  12.0
  24.0
  35.0
  76.0
   0.0
   0.0
   0.0

In [10]:
x

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [11]:
function padwithzeros!(vector, n)
    for i in 1:n
        insert!(vector, 1, 0)
    end 

    for i in 1:n
        append!(vector, 0)
    end
end

padwithzeros! (generic function with 1 method)

In [13]:
padwithzeros!(x, 3)

In [14]:
x

14-element Vector{Int64}:
   0
   0
   0
 -45
 -43
 -36
   3
  12
  24
  35
  76
   0
   0
   0