## Exercise 1
Calculate the optimum beta = (X'X)^-1X'y


In [48]:
X = rand(Float64, (100, 3))

100×3 Matrix{Float64}:
 0.143318    0.143791  0.825903
 0.843689    0.366125  0.602324
 0.470805    0.354731  0.341542
 0.128761    0.667092  0.123801
 0.246463    0.76883   0.493734
 0.0429528   0.151752  0.455854
 0.489084    0.319283  0.727359
 0.779548    0.720568  0.49204
 0.00886793  0.511158  0.270547
 0.675857    0.96161   0.923728
 ⋮                     
 0.505853    0.342105  0.705128
 0.693485    0.693084  0.199086
 0.272465    0.150829  0.424615
 0.280768    0.786311  0.543815
 0.475668    0.869285  0.555805
 0.970203    0.143846  0.0865903
 0.846267    0.812023  0.33992
 0.587369    0.259444  0.83901
 0.140629    0.182501  0.620778

In [49]:
y = rand(100)

100-element Vector{Float64}:
 0.4539486251093585
 0.14455396117680042
 0.6776928454024328
 0.5706711989609492
 0.38721888381376135
 0.08258486451299762
 0.32006383128033733
 0.6542087531925711
 0.6754743097594118
 0.6020584944191777
 ⋮
 0.9188284497561784
 0.7285660819053713
 0.45413834802113895
 0.016508492118265883
 0.9054445793433935
 0.44109659794635125
 0.3608045675321433
 0.44348454510603885
 0.9916126513378248

In [83]:
# β = (X'X)^-1X'y

## Exercise 2 

Create a tuple with your name, age, favorite color, and favorite food. Print the tuple. Extract and print just the name and favorite color.

In [51]:
Details = (Name = "Adedeji Goodness", Age = 26, Favourite_color = "Blue", Favourite_food = "Swalow")

(Name = "Adedeji Goodness", Age = 26, Favourite_color = "Blue", Favourite_food = "Swalow")

In [52]:
Details[1]

"Adedeji Goodness"

In [53]:
Details[3]

"Blue"

## Exercise 3

Create a dictionary with keys as country names and values as their capitals. Add at least 5 countries. Print the dictionary keys and values separately. Write a country name as a variable and print the country and it's capital together. Your code should print "not found" if the country is not among the keys of the dictionary.

In [54]:
Country = Dict("Nigeria" => "Abuja", "Ethopia" => "Addis Ababa", "Ghana" => "Acdra", "Algeria" => "Algiers", "Egypt" => "Cairo", "Senegal" => "Darka")

Dict{String, String} with 6 entries:
  "Ghana"   => "Acdra"
  "Ethopia" => "Addis Ababa"
  "Senegal" => "Darka"
  "Algeria" => "Algiers"
  "Nigeria" => "Abuja"
  "Egypt"   => "Cairo"

In [55]:
# Country["Nigeria"]

keys(Country)

KeySet for a Dict{String, String} with 6 entries. Keys:
  "Ghana"
  "Ethopia"
  "Senegal"
  "Algeria"
  "Nigeria"
  "Egypt"

In [56]:
values(Country)

ValueIterator for a Dict{String, String} with 6 entries. Values:
  "Acdra"
  "Addis Ababa"
  "Darka"
  "Algiers"
  "Abuja"
  "Cairo"

In [57]:
get(Country, "Nigeria", "Not Found")

"Abuja"

## Exercise 4

Create an array with 10 random integers between 1 and 100. Print the array. Find all elements divisible by 5 and print them.

In [58]:
# Score = {Int64}(1:100, 10)
# Score = Array{Int64, 10}(1:100, 10)
Arr = rand(1:60, 10);

In [59]:
print(Arr)

[31, 27, 55, 22, 28, 51, 21, 7, 58, 25]

In [60]:
Arr .% 5

10-element Vector{Int64}:
 1
 2
 0
 2
 3
 1
 1
 2
 3
 0

## Exercise 5

Generate a 5x5 matrix with values from 1 to 25. Print the matrix. Extract and print the diagonals. Find the sum of the matrix.

In [61]:
Mat1 = rand(1:25, (5,5))

5×5 Matrix{Int64}:
 20  12  19   5  17
 23  19   6  18   7
  5   6  12   4   3
  5   9  18  11  19
 23   3  18   3  25

In [62]:
using LinearAlgebra 

idnt = I(5)

5×5 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  1

In [63]:
Mat2 = Mat1 .* idnt

5×5 Matrix{Int64}:
 20   0   0   0   0
  0  19   0   0   0
  0   0  12   0   0
  0   0   0  11   0
  0   0   0   0  25

In [64]:
diag(Mat2)

5-element Vector{Int64}:
 20
 19
 12
 11
 25

In [65]:
sum(Mat2)

87

## Exercise 6

Create a 3D array with 2 layers, each layer a 4x4 matrix with integer values. Print the size. Extract and print one value from the second layer.

In [66]:
Mat3 = reshape(Vector(1:32), (4, 4, 2))

4×4×2 Array{Int64, 3}:
[:, :, 1] =
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

[:, :, 2] =
 17  21  25  29
 18  22  26  30
 19  23  27  31
 20  24  28  32

In [67]:
size(Mat3)

(4, 4, 2)

In [68]:
Mat3[3, 3, 2]

27

## Exercise 7

Convert the array [1, 2, 2, 3, 4, 5] to a set to get unique elements. Take the union and intersection of this set and set([3, 5, 7]).

In [69]:
Arr2 = [1, 2, 2, 3, 4, 5]

6-element Vector{Int64}:
 1
 2
 2
 3
 4
 5

In [70]:
set1 = Set(Arr2)

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [71]:
set2 = [3, 5, 7]

3-element Vector{Int64}:
 3
 5
 7

In [72]:
union(set1, set2)

Set{Int64} with 6 elements:
  5
  4
  7
  2
  3
  1

## Exercise 8 

Define a 3x3 matrix. Find its transpose, determinant and inverse. Multiply the matrix with its inverse and print the result.

In [73]:
Mat4 = rand(1:10, 3, 3)

3×3 Matrix{Int64}:
 7  2  1
 6  9  1
 6  5  1

In [74]:
transpose(Mat4)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 7  6  6
 2  9  5
 1  1  1

In [75]:
det(Mat4)

4.000000000000003

In [77]:
tr(Mat4)

17

In [80]:
Invmat = inv(Mat4)

3×3 Matrix{Float64}:
  1.0           0.75  -1.75
 -5.55112e-17   0.25  -0.25
 -6.0          -5.75  12.75

In [81]:
Mat4 * Invmat

3×3 Matrix{Float64}:
  1.0          0.0   0.0
 -8.88178e-16  1.0  -1.77636e-15
  0.0          0.0   1.0