In [1]:
cvec = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
rvec = [1 2 3 4 5]

1×5 Matrix{Int64}:
 1  2  3  4  5

In [3]:
mat = [1 2 3; 4 5 6; 7 8 9; 10 11 12]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [4]:
mat2 = [1 2 3
        4 5 6
        7 8 9 
        10 11 12
        ]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [5]:
cvec = [1; 2; 3; 4; 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [6]:
ndims(cvec)

1

In [7]:
ndims(rvec)

2

In [15]:
# ndims(mat)
ndims(mat2)

2

In [9]:
size(cvec)

(5,)

In [11]:
size(rvec)

(1, 5)

In [13]:
size(mat)

(4, 3)

In [16]:
size(mat, 1)

4

In [17]:
size(mat, 2)

3

In [19]:
length(mat)

12

Idexing in matrices takes in two input in the []. i.e

+ To idex element in row 2 column 3, use mat[2, 3]

In [22]:
mat[2, 3]

6

In [24]:
mat[end, end]

12

In [25]:
mat[3]

7

In [26]:
mat[5]

2

In [27]:
mat[2:4, 2:3]

3×2 Matrix{Int64}:
  5   6
  8   9
 11  12

In [29]:
# To index the entire row
mat[2, :]

3-element Vector{Int64}:
 4
 5
 6

In [30]:
# This is to index the ewntire column 
mat[:, 3]

4-element Vector{Int64}:
  3
  6
  9
 12

In [7]:
cvec1 = [1, 2, 3, 4, 5]
cvec2 = [6, 7, 8, 9, 10]
cvec3 = [11, 12, 13, 14, 15];


# println(typeof(cvec1))
# print(cvec2)

5-element Vector{Int64}:
 11
 12
 13
 14
 15

In [5]:
vcat(cvec1, cvec2, cvec3)

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [8]:
hcat(cvec1, cvec2, cvec3)

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [9]:
rvec1 = [1 2 3 4 5]
rvec2 = [6 7 8 9 10]
rvec3 = [11 12 13 14 15];

In [10]:
vcat(rvec1, rvec2, rvec3)

3×5 Matrix{Int64}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [11]:
hcat(rvec1, rvec2, rvec3)

1×15 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10  11  12  13  14  15

In [17]:
[cvec1; cvec2; cvec3]

15-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [18]:
[cvec1, cvec2, cvec3]

3-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]

In [20]:
[cvec1 cvec2 cvec3]

5×3 Matrix{Int64}:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [21]:
m1 = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [22]:
m2 = [11 12 13; 14 15 16]

2×3 Matrix{Int64}:
 11  12  13
 14  15  16

In [23]:
# To create vertical concatenation 
mver = [m1; m2]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
 11  12  13
 14  15  16

In [25]:
# to develop horizontal concatenation
mhor = [m1 m2]

2×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16

In [26]:
emptymat = Matrix(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [27]:
Matrix{Any}(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [28]:
Matrix{Float64}(undef, 3, 2)

3×2 Matrix{Float64}:
 3.0e-323  4.0e-323
 3.5e-323  1.0e-323
 4.0e-323  5.4e-323

In [45]:
mat = Matrix{Union{Int64, String}}(undef, (3, 4))

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [46]:
mat[2, 3] = 999;
mat[1, 2] = "number";
mat[3, 3] = "come"

"come"

In [41]:
mat

3×4 Matrix{Union{Int64, String}}:
 #undef     "number"  #undef     #undef
 #undef  #undef       999        #undef
 #undef  #undef          "come"  #undef

In [43]:
# Nothing datatype is used when there is no value to rerurn
# It's just a placeholder
# nothing is an instance of the type Nothing
nothing



In [44]:
typeof(nothing)

Nothing

In [47]:
Matrix{Any}(nothing, (2, 3))

2×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [48]:
Matrix{Union{Int64, Nothing}}(nothing, (2, 3))

2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [49]:
missing

missing

In [50]:
typeof(missing)

Missing

In [51]:
Matrix{Union{Missing, String}}(missing, (2,3))

2×3 Matrix{Union{Missing, String}}:
 missing  missing  missing
 missing  missing  missing

In [54]:
test = reshape(1:15, 3, 5)

3×5 reshape(::UnitRange{Int64}, 3, 5) with eltype Int64:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [56]:
reshape(test, (5,3))

5×3 reshape(::UnitRange{Int64}, 5, 3) with eltype Int64:
 1   6  11
 2   7  12
 3   8  13
 4   9  14
 5  10  15

In [57]:
zeros(2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [58]:
ones(2, 3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [59]:
ones(Int32, 2, 3)

2×3 Matrix{Int32}:
 1  1  1
 1  1  1

In [60]:
trues(2, 3)

2×3 BitMatrix:
 1  1  1
 1  1  1

In [61]:
falses(2,2)

2×2 BitMatrix:
 0  0
 0  0

In [62]:
fill(3.14, (3,2))

3×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14
 3.14  3.14

In [65]:
rand(1:20, (4,3))

4×3 Matrix{Int64}:
 15  14  10
 18   7   5
  4  15  11
  9   3   9

In [69]:
m1 = reshape(range(12., 23., length = 12), (4,3))

4×3 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 4, 3) with eltype Float64:
 12.0  16.0  20.0
 13.0  17.0  21.0
 14.0  18.0  22.0
 15.0  19.0  23.0

In [70]:
m2 = similar(m1)

4×3 Matrix{Float64}:
 3.0e-323  4.0e-323  7.0e-323
 3.5e-323  5.4e-323  7.4e-323
 4.0e-323  6.0e-323  7.4e-323
 4.0e-323  6.4e-323  7.4e-323

In [73]:
m3 = similar(m2, 3,3)

3×3 Matrix{Float64}:
 6.66631e-310  6.66631e-310  6.66631e-310
 6.66631e-310  6.66631e-310  6.66631e-310
 6.66631e-310  6.66631e-310  0.0