Multiplication Tables

In [2]:
outer(v, w) = [x * y for x in v, y in w]

outer (generic function with 1 method)

In [3]:
outer(1:10, 1:10)

10×10 Matrix{Int64}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

In [ ]:
@bind k Slider(1:14, show_value = true)
outer(1:k, 1:k)

In [5]:
outer([2,4,6], [10,100,1000])

3×3 Matrix{Int64}:
 20  200  2000
 40  400  4000
 60  600  6000

In [9]:
flag = outer([1, 0.1, 2], ones(5))

3×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 0.1  0.1  0.1  0.1  0.1
 2.0  2.0  2.0  2.0  2.0

In [ ]:
show_image(flag)

In [12]:
flag2 = outer([1, 0.1, 2], [1, 1, 1, 3, 3, 3])

3×6 Matrix{Float64}:
 1.0  1.0  1.0  3.0  3.0  3.0
 0.1  0.1  0.1  0.3  0.3  0.3
 2.0  2.0  2.0  6.0  6.0  6.0